const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USERNAME_EXISTS: "AUTH_USERNAME_EXISTS",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_INVALID_EMAIL: "AUTH_INVALID_EMAIL",
  AUTH_PASSWORD_WEAK: "AUTH_PASSWORD_WEAK",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_SESSION_INVALID: "AUTH_SESSION_INVALID",
  SYS_INTERNAL_ERROR: "SYS_INTERNAL_ERROR",
};

module.exports = ERROR_CODES;
